name: Test Environment Secrets

on:
    # 手动触发工作流
    workflow_dispatch:

jobs:
    test-secrets:
        runs-on: ubuntu-latest
        # 指定使用的环境 - 请将"您的环境名称"替换为您实际创建的环境名称
        environment: ml-monitor
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Test Docker Hub credentials
              run: |
                  # 检查凭据是否存在但不显示实际值
                  if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
                    echo "✅ DOCKERHUB_USERNAME 密钥存在"
                    # 显示用户名的前两个字符，其余用*替代
                    echo "用户名前两个字符: ${DOCKERHUB_USERNAME:0:2}$(printf '%*s' $((${#DOCKERHUB_USERNAME}-2)) | tr ' ' '*')"
                  else
                    echo "❌ DOCKERHUB_USERNAME 密钥未设置或为空"
                  fi

                  if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
                    echo "✅ DOCKERHUB_TOKEN 密钥存在"
                    # 显示Token长度
                    echo "Token长度: ${#DOCKERHUB_TOKEN} 字符" 
                  else
                    echo "❌ DOCKERHUB_TOKEN 密钥未设置或为空"
                  fi
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: 尝试登录Docker Hub
              if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: 登录后验证
              if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
              run: |
                  echo "尝试查询Docker Hub信息..."
                  # 简单验证是否已登录
                  docker info | grep "Username"
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
